# This was auto-generated by cppack

MAKEFILES_PATH = mkfiles


.PHONY:
debug: 
	@ $(MAKE) -s -f $(MAKEFILES_PATH)/$@.mk $(RULE)

.PHONY:
release: 
	@ $(MAKE) -s -f $(MAKEFILES_PATH)/$@.mk $(RULE)



.PHONY:
clean: 
	@ rm -rf build
